name: student_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_downloader: ^1.11.6
  cupertino_icons: ^1.0.8
  auto_route: ^10.0.1
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  file_picker: ^9.0.2
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  flutter_svg: ^2.0.17
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  logger: ^2.5.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.4
  cached_network_svg_image: ^1.2.0
  pinput: ^5.0.1
  infinite_widgets: ^2.0.2
  rename: ^3.0.2
  package_info_plus: ^8.3.0
  firebase_core: ^3.12.1
  device_info_plus: ^11.3.3
  dropdown_search: ^6.0.2
  equatable: ^2.0.7
  carousel_slider: ^5.0.0
  sleek_circular_slider: ^2.0.1
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  video_player: ^2.10.0
  sqflite: ^2.3.0
  path: ^1.8.3
  file_encrypter: ^2.0.1
  media_kit: ^1.1.10
  media_kit_video: ^1.1.8
  media_kit_libs_android_video: ^1.3.7
  y_player: ^2.0.5+1
  youtube_muxer_2025:
    path: ./youtube_muxer_2025
  
  youtube_player_flutter: ^9.1.1

  root_checker_plus: ^0.0.4
  collection: ^1.19.1
  intl: ^0.19.0
  widgets_easier: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  auto_route_generator: ^10.0.1

flutter_gen:
  output: lib/core/managers/assets

  integrations:
    flutter_svg: true
    lottie: true
    rive: false

  assets:
    outputs:
      class_name: AssetsManager

  fonts:
    enabled: false

  colors:
    enabled: false

flutter:
  uses-material-design: true

  assets:
    # images
    - assets/images/
    - assets/images/onboarding/
    - assets/images/temp/
    - assets/translations/
    - assets/svg/
    - assets/svg/navbar/
    - assets/svg/settings/
    - assets/icons/

  fonts:
    - family: TheSans
      fonts:
        - asset: assets/fonts/TheSans.ttf
